from __future__ import annotations

import os
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken


class UserStoreError(RuntimeError):
    pass


@dataclass(frozen=True)
class ReaCredentials:
    login: str
    password: str


@dataclass(frozen=True)
class StoredCredentials:
    telegram_user_id: int
    login: str
    password: str


@dataclass(frozen=True)
class PendingLogin:
    telegram_user_id: int
    login: str
    pending_action: str | None = None


@dataclass(frozen=True)
class RatingSnapshot:
    subject: str
    total: str
    attendance: str | None = None
    control: str | None = None
    creative: str | None = None
    intermediate: str | None = None


@dataclass(frozen=True)
class ScheduleSnapshot:
    telegram_user_id: int
    schedule_hash: str
    schedule_text: str
    schedule_key: str | None = None


class UserStore:
    def __init__(self) -> None:
        self.database_url = os.getenv("DATABASE_URL", "").strip()
        self.use_postgres = self.database_url.startswith(("postgres://", "postgresql://"))

        if not self.use_postgres:
            db_path = os.getenv("BOT_DB_PATH", "credentials.sqlite3")
            self.db_path = Path(db_path)
            self.db_path.parent.mkdir(parents=True, exist_ok=True)

        key = os.getenv("BOT_CREDENTIAL_KEY", "").strip()
        if not key:
            raise UserStoreError("BOT_CREDENTIAL_KEY не задан в .env")

        self.cipher = Fernet(key.encode("utf-8"))
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self.db_path)

    def _pg_connect(self):
        try:
            import psycopg
        except ImportError as exc:
            raise UserStoreError("Для DATABASE_URL нужен пакет psycopg.") from exc

        return psycopg.connect(self.database_url)

    def _init_db(self) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS rea_credentials (
                            telegram_user_id BIGINT PRIMARY KEY,
                            rea_login TEXT NOT NULL,
                            rea_password_encrypted BYTEA NOT NULL,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS bot_events (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            telegram_user_id BIGINT,
                            event_type TEXT NOT NULL,
                            message_text TEXT,
                            subject_query TEXT,
                            subject_matched TEXT,
                            result_status TEXT,
                            response_text TEXT,
                            error_message TEXT,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE INDEX IF NOT EXISTS idx_bot_events_created_at
                        ON bot_events (created_at DESC)
                        """
                    )
                    cursor.execute(
                        """
                        CREATE INDEX IF NOT EXISTS idx_bot_events_telegram_user_id
                        ON bot_events (telegram_user_id)
                        """
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS rating_snapshots (
                            telegram_user_id BIGINT NOT NULL,
                            subject TEXT NOT NULL,
                            total TEXT NOT NULL,
                            attendance TEXT,
                            control TEXT,
                            creative TEXT,
                            intermediate TEXT,
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            PRIMARY KEY (telegram_user_id, subject)
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE INDEX IF NOT EXISTS idx_rating_snapshots_user_id
                        ON rating_snapshots (telegram_user_id)
                        """
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS user_settings (
                            telegram_user_id BIGINT PRIMARY KEY,
                            notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS pending_logins (
                            telegram_user_id BIGINT PRIMARY KEY,
                            rea_login TEXT NOT NULL,
                            pending_action TEXT,
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS schedule_snapshots (
                            telegram_user_id BIGINT PRIMARY KEY,
                            schedule_key TEXT,
                            schedule_hash TEXT NOT NULL,
                            schedule_text TEXT NOT NULL,
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                        """
                    )
                    cursor.execute(
                        """
                        ALTER TABLE schedule_snapshots
                        ADD COLUMN IF NOT EXISTS schedule_key TEXT
                        """
                    )
            return

        with self._connect() as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS rea_credentials (
                    telegram_user_id INTEGER PRIMARY KEY,
                    rea_login TEXT NOT NULL,
                    rea_password_encrypted BLOB NOT NULL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS bot_events (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    telegram_user_id INTEGER,
                    event_type TEXT NOT NULL,
                    message_text TEXT,
                    subject_query TEXT,
                    subject_matched TEXT,
                    result_status TEXT,
                    response_text TEXT,
                    error_message TEXT,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_bot_events_created_at
                ON bot_events (created_at DESC)
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_bot_events_telegram_user_id
                ON bot_events (telegram_user_id)
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS rating_snapshots (
                    telegram_user_id INTEGER NOT NULL,
                    subject TEXT NOT NULL,
                    total TEXT NOT NULL,
                    attendance TEXT,
                    control TEXT,
                    creative TEXT,
                    intermediate TEXT,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (telegram_user_id, subject)
                )
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_rating_snapshots_user_id
                ON rating_snapshots (telegram_user_id)
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS user_settings (
                    telegram_user_id INTEGER PRIMARY KEY,
                    notifications_enabled INTEGER NOT NULL DEFAULT 1,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS pending_logins (
                    telegram_user_id INTEGER PRIMARY KEY,
                    rea_login TEXT NOT NULL,
                    pending_action TEXT,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS schedule_snapshots (
                    telegram_user_id INTEGER PRIMARY KEY,
                    schedule_key TEXT,
                    schedule_hash TEXT NOT NULL,
                    schedule_text TEXT NOT NULL,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            columns = {
                row[1]
                for row in connection.execute("PRAGMA table_info(schedule_snapshots)").fetchall()
            }
            if "schedule_key" not in columns:
                connection.execute("ALTER TABLE schedule_snapshots ADD COLUMN schedule_key TEXT")

    def log_event(
        self,
        *,
        telegram_user_id: int | None,
        event_type: str,
        message_text: str | None = None,
        subject_query: str | None = None,
        subject_matched: str | None = None,
        result_status: str | None = None,
        response_text: str | None = None,
        error_message: str | None = None,
    ) -> None:
        values = (
            telegram_user_id,
            event_type,
            _limit_text(message_text),
            _limit_text(subject_query),
            _limit_text(subject_matched),
            _limit_text(result_status, 100),
            _limit_text(response_text),
            _limit_text(error_message),
        )

        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        INSERT INTO bot_events (
                            telegram_user_id,
                            event_type,
                            message_text,
                            subject_query,
                            subject_matched,
                            result_status,
                            response_text,
                            error_message
                        )
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        values,
                    )
            return

        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO bot_events (
                    telegram_user_id,
                    event_type,
                    message_text,
                    subject_query,
                    subject_matched,
                    result_status,
                    response_text,
                    error_message
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                values,
            )

    def get_credentials(self, telegram_user_id: int) -> ReaCredentials | None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT rea_login, rea_password_encrypted
                        FROM rea_credentials
                        WHERE telegram_user_id = %s
                        """,
                        (telegram_user_id,),
                    )
                    row = cursor.fetchone()

            if row is None:
                return None

            login, encrypted_password = row
            try:
                password = self.cipher.decrypt(bytes(encrypted_password)).decode("utf-8")
            except InvalidToken:
                self.delete_credentials(telegram_user_id)
                return None
            return ReaCredentials(login=login, password=password)

        with self._connect() as connection:
            row = connection.execute(
                """
                SELECT rea_login, rea_password_encrypted
                FROM rea_credentials
                WHERE telegram_user_id = ?
                """,
                (telegram_user_id,),
            ).fetchone()

        if row is None:
            return None

        login, encrypted_password = row
        try:
            password = self.cipher.decrypt(encrypted_password).decode("utf-8")
        except InvalidToken:
            self.delete_credentials(telegram_user_id)
            return None
        return ReaCredentials(login=login, password=password)

    def list_credentials(self) -> list[StoredCredentials]:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT telegram_user_id, rea_login, rea_password_encrypted
                        FROM rea_credentials
                        ORDER BY updated_at ASC
                        """
                    )
                    rows = cursor.fetchall()
        else:
            with self._connect() as connection:
                rows = connection.execute(
                    """
                    SELECT telegram_user_id, rea_login, rea_password_encrypted
                    FROM rea_credentials
                    ORDER BY updated_at ASC
                    """
                ).fetchall()

        credentials: list[StoredCredentials] = []
        invalid_user_ids: list[int] = []
        for telegram_user_id, login, encrypted_password in rows:
            try:
                password = self.cipher.decrypt(bytes(encrypted_password)).decode("utf-8")
            except InvalidToken:
                invalid_user_ids.append(int(telegram_user_id))
                continue
            credentials.append(
                StoredCredentials(
                    telegram_user_id=int(telegram_user_id),
                    login=login,
                    password=password,
                )
            )

        for telegram_user_id in invalid_user_ids:
            self.delete_credentials(telegram_user_id)

        return credentials

    def list_notification_credentials(self) -> list[StoredCredentials]:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT c.telegram_user_id, c.rea_login, c.rea_password_encrypted
                        FROM rea_credentials AS c
                        LEFT JOIN user_settings AS s
                          ON s.telegram_user_id = c.telegram_user_id
                        WHERE COALESCE(s.notifications_enabled, TRUE) = TRUE
                        ORDER BY c.updated_at ASC
                        """
                    )
                    rows = cursor.fetchall()
        else:
            with self._connect() as connection:
                rows = connection.execute(
                    """
                    SELECT c.telegram_user_id, c.rea_login, c.rea_password_encrypted
                    FROM rea_credentials AS c
                    LEFT JOIN user_settings AS s
                      ON s.telegram_user_id = c.telegram_user_id
                    WHERE COALESCE(s.notifications_enabled, 1) = 1
                    ORDER BY c.updated_at ASC
                    """
                ).fetchall()

        credentials: list[StoredCredentials] = []
        invalid_user_ids: list[int] = []
        for telegram_user_id, login, encrypted_password in rows:
            try:
                password = self.cipher.decrypt(bytes(encrypted_password)).decode("utf-8")
            except InvalidToken:
                invalid_user_ids.append(int(telegram_user_id))
                continue
            credentials.append(
                StoredCredentials(
                    telegram_user_id=int(telegram_user_id),
                    login=login,
                    password=password,
                )
            )

        for telegram_user_id in invalid_user_ids:
            self.delete_credentials(telegram_user_id)

        return credentials

    def notifications_enabled(self, telegram_user_id: int) -> bool:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT notifications_enabled
                        FROM user_settings
                        WHERE telegram_user_id = %s
                        """,
                        (telegram_user_id,),
                    )
                    row = cursor.fetchone()
        else:
            with self._connect() as connection:
                row = connection.execute(
                    """
                    SELECT notifications_enabled
                    FROM user_settings
                    WHERE telegram_user_id = ?
                    """,
                    (telegram_user_id,),
                ).fetchone()

        if row is None:
            return True
        return bool(row[0])

    def list_notification_settings(self) -> dict[int, bool]:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT telegram_user_id, notifications_enabled
                        FROM user_settings
                        """
                    )
                    rows = cursor.fetchall()
        else:
            with self._connect() as connection:
                rows = connection.execute(
                    """
                    SELECT telegram_user_id, notifications_enabled
                    FROM user_settings
                    """
                ).fetchall()

        return {int(telegram_user_id): bool(enabled) for telegram_user_id, enabled in rows}

    def set_notifications_enabled(self, telegram_user_id: int, enabled: bool) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        INSERT INTO user_settings (
                            telegram_user_id,
                            notifications_enabled
                        )
                        VALUES (%s, %s)
                        ON CONFLICT(telegram_user_id) DO UPDATE SET
                            notifications_enabled = EXCLUDED.notifications_enabled,
                            updated_at = CURRENT_TIMESTAMP
                        """,
                        (telegram_user_id, enabled),
                    )
            return

        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO user_settings (
                    telegram_user_id,
                    notifications_enabled
                )
                VALUES (?, ?)
                ON CONFLICT(telegram_user_id) DO UPDATE SET
                    notifications_enabled = excluded.notifications_enabled,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (telegram_user_id, int(enabled)),
            )

    def toggle_notifications_enabled(self, telegram_user_id: int) -> bool:
        enabled = not self.notifications_enabled(telegram_user_id)
        self.set_notifications_enabled(telegram_user_id, enabled)
        return enabled

    def save_pending_login(
        self,
        *,
        telegram_user_id: int,
        rea_login: str,
        pending_action: str | None = None,
    ) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        INSERT INTO pending_logins (
                            telegram_user_id,
                            rea_login,
                            pending_action
                        )
                        VALUES (%s, %s, %s)
                        ON CONFLICT(telegram_user_id) DO UPDATE SET
                            rea_login = EXCLUDED.rea_login,
                            pending_action = EXCLUDED.pending_action,
                            updated_at = CURRENT_TIMESTAMP
                        """,
                        (telegram_user_id, rea_login, pending_action),
                    )
            return

        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO pending_logins (
                    telegram_user_id,
                    rea_login,
                    pending_action
                )
                VALUES (?, ?, ?)
                ON CONFLICT(telegram_user_id) DO UPDATE SET
                    rea_login = excluded.rea_login,
                    pending_action = excluded.pending_action,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (telegram_user_id, rea_login, pending_action),
            )

    def get_pending_login(self, telegram_user_id: int) -> PendingLogin | None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT rea_login, pending_action
                        FROM pending_logins
                        WHERE telegram_user_id = %s
                        """,
                        (telegram_user_id,),
                    )
                    row = cursor.fetchone()
        else:
            with self._connect() as connection:
                row = connection.execute(
                    """
                    SELECT rea_login, pending_action
                    FROM pending_logins
                    WHERE telegram_user_id = ?
                    """,
                    (telegram_user_id,),
                ).fetchone()

        if row is None:
            return None

        return PendingLogin(
            telegram_user_id=telegram_user_id,
            login=row[0],
            pending_action=row[1],
        )

    def delete_pending_login(self, telegram_user_id: int) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        "DELETE FROM pending_logins WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
            return

        with self._connect() as connection:
            connection.execute(
                "DELETE FROM pending_logins WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )

    def get_rating_snapshots(self, telegram_user_id: int) -> dict[str, RatingSnapshot]:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT subject, total, attendance, control, creative, intermediate
                        FROM rating_snapshots
                        WHERE telegram_user_id = %s
                        """,
                        (telegram_user_id,),
                    )
                    rows = cursor.fetchall()
        else:
            with self._connect() as connection:
                rows = connection.execute(
                    """
                    SELECT subject, total, attendance, control, creative, intermediate
                    FROM rating_snapshots
                    WHERE telegram_user_id = ?
                    """,
                    (telegram_user_id,),
                ).fetchall()

        return {
            row[0]: RatingSnapshot(
                subject=row[0],
                total=row[1],
                attendance=row[2],
                control=row[3],
                creative=row[4],
                intermediate=row[5],
            )
            for row in rows
        }

    def list_rating_snapshots(self) -> dict[int, dict[str, RatingSnapshot]]:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT telegram_user_id, subject, total, attendance, control, creative, intermediate
                        FROM rating_snapshots
                        ORDER BY telegram_user_id, subject
                        """
                    )
                    rows = cursor.fetchall()
        else:
            with self._connect() as connection:
                rows = connection.execute(
                    """
                    SELECT telegram_user_id, subject, total, attendance, control, creative, intermediate
                    FROM rating_snapshots
                    ORDER BY telegram_user_id, subject
                    """
                ).fetchall()

        snapshots_by_user: dict[int, dict[str, RatingSnapshot]] = {}
        for telegram_user_id, subject, total, attendance, control, creative, intermediate in rows:
            user_snapshots = snapshots_by_user.setdefault(int(telegram_user_id), {})
            user_snapshots[subject] = RatingSnapshot(
                subject=subject,
                total=total,
                attendance=attendance,
                control=control,
                creative=creative,
                intermediate=intermediate,
            )
        return snapshots_by_user

    def replace_rating_snapshots(
        self,
        *,
        telegram_user_id: int,
        snapshots: list[RatingSnapshot],
    ) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        "DELETE FROM rating_snapshots WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
                    for snapshot in snapshots:
                        cursor.execute(
                            """
                            INSERT INTO rating_snapshots (
                                telegram_user_id,
                                subject,
                                total,
                                attendance,
                                control,
                                creative,
                                intermediate
                            )
                            VALUES (%s, %s, %s, %s, %s, %s, %s)
                            """,
                            (
                                telegram_user_id,
                                snapshot.subject,
                                snapshot.total,
                                snapshot.attendance,
                                snapshot.control,
                                snapshot.creative,
                                snapshot.intermediate,
                            ),
                        )
            return

        with self._connect() as connection:
            connection.execute(
                "DELETE FROM rating_snapshots WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )
            for snapshot in snapshots:
                connection.execute(
                    """
                    INSERT INTO rating_snapshots (
                        telegram_user_id,
                        subject,
                        total,
                        attendance,
                        control,
                        creative,
                        intermediate
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        telegram_user_id,
                        snapshot.subject,
                        snapshot.total,
                        snapshot.attendance,
                        snapshot.control,
                        snapshot.creative,
                        snapshot.intermediate,
                    ),
                )

    def save_credentials(
        self,
        *,
        telegram_user_id: int,
        rea_login: str,
        rea_password: str,
    ) -> None:
        encrypted_password = self.cipher.encrypt(rea_password.encode("utf-8"))
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        INSERT INTO rea_credentials (
                            telegram_user_id,
                            rea_login,
                            rea_password_encrypted
                        )
                        VALUES (%s, %s, %s)
                        ON CONFLICT(telegram_user_id) DO UPDATE SET
                            rea_login = EXCLUDED.rea_login,
                            rea_password_encrypted = EXCLUDED.rea_password_encrypted,
                            updated_at = CURRENT_TIMESTAMP
                        """,
                        (telegram_user_id, rea_login, encrypted_password),
                    )
            return

        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO rea_credentials (
                    telegram_user_id,
                    rea_login,
                    rea_password_encrypted
                )
                VALUES (?, ?, ?)
                ON CONFLICT(telegram_user_id) DO UPDATE SET
                    rea_login = excluded.rea_login,
                    rea_password_encrypted = excluded.rea_password_encrypted,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (telegram_user_id, rea_login, encrypted_password),
            )

    def get_schedule_snapshot(self, telegram_user_id: int) -> ScheduleSnapshot | None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT schedule_hash, schedule_text, schedule_key
                        FROM schedule_snapshots
                        WHERE telegram_user_id = %s
                        """,
                        (telegram_user_id,),
                    )
                    row = cursor.fetchone()
        else:
            with self._connect() as connection:
                row = connection.execute(
                    """
                    SELECT schedule_hash, schedule_text, schedule_key
                    FROM schedule_snapshots
                    WHERE telegram_user_id = ?
                    """,
                    (telegram_user_id,),
                ).fetchone()

        if row is None:
            return None

        return ScheduleSnapshot(
            telegram_user_id=telegram_user_id,
            schedule_hash=row[0],
            schedule_text=row[1],
            schedule_key=row[2],
        )

    def list_schedule_snapshots(self) -> dict[int, ScheduleSnapshot]:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        SELECT telegram_user_id, schedule_hash, schedule_text, schedule_key
                        FROM schedule_snapshots
                        """
                    )
                    rows = cursor.fetchall()
        else:
            with self._connect() as connection:
                rows = connection.execute(
                    """
                    SELECT telegram_user_id, schedule_hash, schedule_text, schedule_key
                    FROM schedule_snapshots
                    """
                ).fetchall()

        return {
            int(telegram_user_id): ScheduleSnapshot(
                telegram_user_id=int(telegram_user_id),
                schedule_hash=schedule_hash,
                schedule_text=schedule_text,
                schedule_key=schedule_key,
            )
            for telegram_user_id, schedule_hash, schedule_text, schedule_key in rows
        }

    def save_schedule_snapshot(
        self,
        *,
        telegram_user_id: int,
        schedule_hash: str,
        schedule_text: str,
        schedule_key: str | None = None,
    ) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        """
                        INSERT INTO schedule_snapshots (
                            telegram_user_id,
                            schedule_key,
                            schedule_hash,
                            schedule_text
                        )
                        VALUES (%s, %s, %s, %s)
                        ON CONFLICT(telegram_user_id) DO UPDATE SET
                            schedule_key = EXCLUDED.schedule_key,
                            schedule_hash = EXCLUDED.schedule_hash,
                            schedule_text = EXCLUDED.schedule_text,
                            updated_at = CURRENT_TIMESTAMP
                        """,
                        (telegram_user_id, schedule_key, schedule_hash, schedule_text),
                    )
            return

        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO schedule_snapshots (
                    telegram_user_id,
                    schedule_key,
                    schedule_hash,
                    schedule_text
                )
                VALUES (?, ?, ?, ?)
                ON CONFLICT(telegram_user_id) DO UPDATE SET
                    schedule_key = excluded.schedule_key,
                    schedule_hash = excluded.schedule_hash,
                    schedule_text = excluded.schedule_text,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (telegram_user_id, schedule_key, schedule_hash, schedule_text),
            )

    def delete_credentials(self, telegram_user_id: int) -> None:
        if self.use_postgres:
            with self._pg_connect() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        "DELETE FROM rea_credentials WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
                    cursor.execute(
                        "DELETE FROM rating_snapshots WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
                    cursor.execute(
                        "DELETE FROM schedule_snapshots WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
                    cursor.execute(
                        "DELETE FROM user_settings WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
                    cursor.execute(
                        "DELETE FROM pending_logins WHERE telegram_user_id = %s",
                        (telegram_user_id,),
                    )
            return

        with self._connect() as connection:
            connection.execute(
                "DELETE FROM rea_credentials WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )
            connection.execute(
                "DELETE FROM rating_snapshots WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )
            connection.execute(
                "DELETE FROM schedule_snapshots WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )
            connection.execute(
                "DELETE FROM user_settings WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )
            connection.execute(
                "DELETE FROM pending_logins WHERE telegram_user_id = ?",
                (telegram_user_id,),
            )


def _limit_text(value: str | None, limit: int = 2000) -> str | None:
    if value is None:
        return None
    value = str(value)
    if len(value) <= limit:
        return value
    return f"{value[:limit]}..."
